version: '3'
volumes:
  postgres_data:
    driver: local
services:
    kcpostgres:
      image: postgres:latest
      hostname: kcpostgres
      container_name: kcpostgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      ports:
        - 5433:5432
    
    keycloak:
      image: jboss/keycloak:latest
      container_name: keycloak
      hostname: keycloak    
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: kcpostgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
        KEYCLOAK_LOGLEVEL: DEBUG
        ROOT_LOGLEVEL: DEBUG
        KC_HEALTH_ENABLED: true
        KC_METRICS_ENABLED: true
        KC_FEATURES: token-exchange
      env_file:
        - kafka.common.env
      volumes:
        - './keycloak-kafka-1.1.5-jar-with-dependencies.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-kafka-1.1.5-jar-with-dependencies.jar'
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8095/auth/"]
        interval: 5s
        timeout: 2s
        retries: 15
      ports:
        - 8095:8080
        - 8443:8443
      depends_on:
        - kcpostgres
        - broker

    broker:
      image: confluentinc/confluent-local:7.4.1
      hostname: broker
      container_name: broker
      ports:
        - "8082:8082"
        - "9092:9092"
        - "9101:9101"
      environment:
        KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
        KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
        KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'

    kafka-ui:
      image: provectuslabs/kafka-ui:latest
      ports:
        - 9999:8080
      environment:
        DYNAMIC_CONFIG_ENABLED: true
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      depends_on:
        - broker